knowledge_repo/app/routes/polly_api.py
"""
APIs for polly and their routes
Includes:
    - /api/uploadkr
    - /api/uploadpost
    - /api/uploadpage

"""

import os
import json
from builtins import str
from collections import namedtuple
from flask import request, render_template, redirect, Blueprint, current_app, make_response,jsonify,url_for
from flask_login import login_required
from sqlalchemy import case, desc
from sqlalchemy.exc import IntegrityError
from werkzeug import secure_filename
from .. import permissions
from ..proxies import db_session, current_repo
from ..utils.posts import get_posts
from ..models import Post, Tag, User, PageView
from ..utils.requests import from_url_get_feed_params
from ..utils.render import render_post_tldr
from ..utils.s3_talk import download_dir,download_from_s3  
from ..index import update_index, update_index_for_post
blueprint = Blueprint('api', __name__, template_folder='../templates', static_folder='../static')




def publish_post_db(kp,path):
    if not kp.is_valid():
        print("KP was invalid")
        return

    print("Checking the DB for this:",path)
    post = (db_session.query(Post).filter(Post.path==path).first())
    if not post:
        print(u'creating new post from path {}'.format(kp.path))
        post = Post()
        db_session.add(post)
        db_session.commit()
        db_session.flush()  # (matthew) Fix groups logic so this is not necessary
    try:
        post.update_metadata_from_kp(kp)
        print("After update:", post.path)
    except IntegrityError:
        import uuid
        db_session.rollback()
        print("from the caller:",kp.path)
        kp.uuid = str(uuid.uuid4())
        post.update_metadata_from_kp(kp)
        print("After update:", post.path)
    db_session.commit()
    db_session.flush()

        # Record revision
#    for uri, revision in current_repo.revisions.items():
#        IndexMetadata.set('repository_revision', uri, str(revision))

def prep_kr_path(path,dir_name):
    path_parts = path.split('/')
    if '/'.join(path_parts[:2]) != dir_name:
        path = dir_name + '/' + path
    if not path.endswith('.kp'):
        path = path + '.kp'
    return path

def prep_post_path(path):
    if not path.endswith('.kp'):
        path = path + '.kp'
    return path


@blueprint.route('/api/uploadpage')
@PageView.logged
def upload_post_page(): 
    try:
        kr_list = current_app.get_kr_list()
    except ValueError:
        return redirect("https://%s/?next=%s"%(request.host,request.full_path))
    return render_template('upload_page.html',krs = kr_list)

@blueprint.route('/api/uploadpost',methods=['POST'])
def upload_post():
    # Access the file
    #TODO: Put everything in try catch
    tempfile = request.files['file']
    temp_path = os.path.join('/tmp',secure_filename(tempfile.filename))
    tempfile.save(temp_path)
    repo = request.form.get('repo')
    path = repo + '/' + request.form.get('path')
    # Just post the post to the path
    try:
        new_post = current_repo.upload_post(temp_path,path)
    #    update_index_for_post(new_post,path)
        path = prep_post_path(path)
        publish_post_db(new_post,path)
    except:
        return render_template("error.html")
    return redirect(url_for('posts.render',path=path))

@blueprint.route('/api/uploadkr')
@PageView.logged
def upload_kr():
    """
    API to upload a KR to the server
    args:
        S3-Path 
    """
    import shutil
    global current_repo,current_app
    from ...repositories.meta import MetaKnowledgeRepository
    path = request.args.get('path')
    pid = path.split('/')[-2]
    dir_name,dir_path = download_dir(path)
    dir_name = pid + '/' + dir_name
    error = 200
    #try:
    db_path = current_app.config['KR_REPO_DB_PATH'] + ':' +  dir_name
    dbobj  = current_repo.migrate_to_dbrepo(dir_path,db_path)
    current_app.append_repo_obj(dir_name,dbobj)
    temp_kr = MetaKnowledgeRepository({dir_name:dbobj})
    for post in temp_kr.posts():
        post_path = prep_kr_path(post.path,dir_name)
        print("Tried pushing:",post_path)
        publish_post_db(post,post_path)
    #except:
   #TODO: do more precise exception handling
    #    error = 400
    shutil.rmtree(dir_path)
    return jsonify({
                'statusCode': '400' if error==400 else '200',
                'headers': {
                            'Content-Type': 'application/json',
                            'Access-Control-Allow-Origin': '*'
                            },
                   })

knowledge_repo/app/templates/auth-switcher.html
{% extends "base.html" %}

{% block title %}
Knowledge Repo Login
{% endblock %}

{% block extra_headers %}
<link rel='stylesheet' href='{{ url_for("static", filename="css/pages/auth-switcher.css") }}'>
{% endblock %}

{% block navbar %}
<!-- Top-level navbar -->
<nav class="navbar navbar-inverse" style='border-radius: 0px;'>
  <div class="container">
    <div class="navbar-header" style='float:none'>
      <!-- Brand name / logo -->
      <a class="navbar-brand" href="/" class="logo-image">
        <img src='{{ url_for("static", filename="images/logo-black.svg") }}' />
      </a>
    </div>
  </div>
</nav>
{% endblock %}

{% block content %}

<div class='login-form'>
{% if providers %}
  <span class='auth-message'>
    Sign in to Knowledge-Repo
  </span>
  <ul class='auth-providers'>
    {% for provider in providers %}
    <span class='login-option'>
      <li><a href='login/{{ provider['name'] }}?next={{request.args.next}}'><img src='{{ provider['icon_uri'] }}' />{{
          provider['link_text'] }}</a></li>
    </span>
    {% endfor %}
  </ul>
{% else %}
  <span class='auth-message'>
    The content you are attempting to access requires that you are logged in.
    <br><br>
    Unfortunately, there are no authentication mechanisms configured. Please contact your system administrator to enable
    authentication.
  </span>
{% endif %}
</div>

{% endblock %}

knowledge_repo/app/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">

  <title>{% block title %}Knowledge Repo{% endblock %}</title>

  <!-- js includes at the top as post embedded js colliding -->
  <script src="{{ url_for('static', filename='modules/jquery/jquery.min.js')}}"></script>
  <script src="{{ url_for('static', filename='modules/tether/js/tether.min.js')}}"></script>
  <script src="{{ url_for('static', filename='modules/bootstrap/js/bootstrap.min.js')}}"></script>
  <script src="{{ url_for('static', filename='modules/bootstrap-slider/js/bootstrap-slider.min.js')}}"></script>
  <script src="{{ url_for('static', filename='modules/typeahead.js/typeahead.bundle.min.js')}}"></script>
  <script src="{{ url_for('static', filename='modules/handlebars/js/handlebars.js')}}"></script>
  <script src="{{ url_for('static', filename='js/helpers.js')}}"></script>
  <script src="{{ url_for('static', filename='modules/select2/js/select2.min.js')}}"></script>
  <script src="{{ url_for('static', filename='modules/hightlight.pack.js/highlight.pack.js')}}"></script>
  <script src="{{ url_for('static', filename='modules/marked.js/marked.js')}}"></script>
  <!-- Update ID from ENV -->
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-PGDFSCG1GD"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-PGDFSCG1GD');
  </script>
  <!-- require js is used for plotly, but has a bunch of collisions with other js packages
             make sure to have it be last js package imported -->
  <script src="{{ url_for('static', filename='modules/require.js/require.min.js')}}"></script>
  <script src="{{ url_for('static', filename='js/pages/base.js')}}"></script>

  <!-- Set explicit mobile collapse behaviour -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!-- fix for IE compatability mode -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!--[if lt IE 9]>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.2/html5shiv.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/2.1.0/es5-shim.min.js"></script>
        <![endif]-->
  <link rel="stylesheet" href="{{ url_for('static', filename='modules/bootstrap/css/bootstrap.min.css')}}">
  <link rel="stylesheet"
    href="{{ url_for('static', filename='modules/bootstrap-slider/css/bootstrap-slider.min.css')}}">
  <link rel="stylesheet" type='text/css' href="{{ url_for('static', filename='css/pages/base.css') }}">
  <link rel="stylesheet" type='text/css' href="{{ url_for('static', filename='modules/select2/css/select2.min.css') }}">
  <link href='https://fonts.googleapis.com/css?family=Lato:400,900|Playfair+Display|Source+Serif+Pro:400,700'
    rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.png') }}"> {% block style_links %}{%
  endblock %}

  <!-- Favicon and app settings -->
  <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='images/apple-touch-icon.png') }}">
  <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='images/favicon-32x32.png') }}">
  <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='images/favicon-16x16.png') }}">
  <link rel="manifest" href="{{ url_for('static', filename='images/site.manifest') }}">
  <link rel="mask-icon" href="{{ url_for('static', filename='images/safari-pinned-tab.svg') }}" color="#5bbad5">
  <meta name="theme-color" content="#ffffff">

  {% block extra_headers %}
  {% endblock %}
  <style>
    {% block style %}
    {% endblock %}
  </style>
</head>

<body>
  {% block navbar %}
  <!-- Top-level navbar -->
  <nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container-fluid">
      <div class='col-lg-2'></div>
      <div class='col-lg-8'>

        <div class="navbar-header">
          <!-- Hamburger button to display collapsed menu -->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
            aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <!-- Brand name / logo -->
          <a class="navbar-brand" href="/" class="logo-image">
            <img src='{{ url_for("static", filename = "images/logo-black.svg")}}' />
            <text>Knowledge Repo</text>
          </a>
        </div>

        <!-- Navigation items -->
        <div id="navbar" class="navbar-collapse collapse">

          <!-- Search bar -->
          <form class="navbar-form navbar-left searchbar" role="search" action="{{url_for('index.render_feed')}}">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search" name="filters" id="searchbar"
                value="{% if feed_params and feed_params['filters'] %}{{ feed_params['filters'] }}{% endif %}">
              <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
              </div>
            </div>
          </form>

          <!-- "Add a Post" button -->
          <a href="/create" class="btn btn-primary navbar-button">
            Add a Post!
          </a>

          <!-- Drop down menu to surface less used links on large screens -->
          <ul class="nav navbar-nav navbar-right visible-sm-block visible-md-block visible-lg-block">
            <li class="dropdown">
              <a href="#" class="avatar-dropdown dropdown-toggle" data-toggle="dropdown" role="button"
                aria-haspopup="true" aria-expanded="true" style='padding: 5px;'>
                <img class="avatar"
                  src="{% if current_user.is_anonymous %}{{ url_for('static', filename='images/profile_photo_logged_out.png') }}{%else%}{{ current_user.avatar_uri or url_for('static', filename='images/profile_photo_default.png') }}{%endif%}" />
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                {% if current_user.is_authenticated %}
                <li class="dropdown-header">Logged in as <em>{{ current_user.format_name }}</em></li>
                <li><a href="/feed?authors={{ current_user.identifier }}">My Posts</a></li>
                <li><a href="/favorites">My Favorites</a></li>
                {% if current_user.can_logout %}
                <li><a href="{{ url_for('auth.logout') }}">Sign out</a></li>
                {% endif %}
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Site Features</li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Sign in</a></li>
                {% endif %}
                <li><a href="/stats">Stats</a></li>
                <li><a href="http://knowledge-repo.readthedocs.io/" target="_blank"
                    rel="nofollow noreferrer">Documentation</a></li>
              </ul>
            </li>
          </ul>

          <!-- Expose the same links as above in the collapsed navbar header -->
          <ul class="nav navbar-nav navbar-right visible-xs-block">
            {% if current_user.is_authenticated %}
            <li class="dropdown-header">Logged in as <em>{{name}}</em></li>
            <li><a href="/feed?authors={{username}}">My Posts</a></li>
            <li><a href="/favorites">My Favorites</a></li>
            <li role="separator" class="divider"></li>
            {% if current_user.can_logout %}
            <li><a href="{{ url_for('auth.logout') }}">Sign out</a></li>
            {% endif %}
            <li class="dropdown-header">Site Features</li>
            {% else %}
            <li><a href="{{ url_for('auth.login') }}">Sign in</a></li>
            {% endif %}
            <li><a href="/stats">Stats</a></li>
            <li><a href="http://knowledge-repo.readthedocs.io/" target="_blank"
                rel="nofollow noreferrer">Documentation</a></li>
          </ul>

        </div>
      </div>
    </div>
  </nav>
  {% endblock %}

  <!-- Main content place holder, with a sidebar on both the left and right,
         which collapse to form a single column on smaller screens. -->
  <div class="container-fluid page-container">
    <div class='row'>
      <!-- Left sidebar -->
      <div class='col-lg-2'>
        <div class='side-panel' id='panel-left'>
          {% block panel_left %}{% endblock %}
        </div>
      </div>
      <!-- Main content placeholder -->
      <div class='col-lg-7' id='panel-main'>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul class=flashes>
          {% for message in messages %}
          <li>{{ message }}</li>
          {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
        {% block content %} {% endblock %}
      </div>
      <!-- Right sidebar -->
      <div class='col-lg-2'>
        <div class='side-panel' id='panel-right'>
          {% block panel_right %}{% endblock %}
        </div>
      </div>
    </div>
  </div>

  <div class="footer">
    Served with <span class="glyphicon glyphicon-heart"></span> by <a
      href="https://github.com/airbnb/knowledge-repo">Knowledge Repo</a> <a {% if version_revision
      %}title='{{version_revision}}' {% endif %}
      href="https://github.com/airbnb/knowledge-repo/releases/tag/v{{ version }}">{{ version }}</a>
    <br />
    <i title="Last checked for updates: {{last_index_check}}">Last indexed: {{last_index}}</i>
  </div>

  <!-- Placeholder for additional ad-hoc scripts. -->
  {% block scripts %}
  {% endblock %}

</body>

</html>

knowledge_repo/app/templates/index-base.html
{% extends "base.html" %}

{% macro format_authors(authors) %}
{% for author in authors %}
<a href='/feed?authors={{ author.identifier|urlencode }}'>
  {{ author.format_name }}
</a>
{% if not loop.last %}
,
{% endif %}
{% endfor %}
{% endmacro %}

{% macro pagination(max_pages=20, extremes=True, autohide=True) %}
{% if feed_params %}
{% set start = feed_params['start'] | default(0) %}
{% set results = feed_params['results'] | default(10) %}
{% set page = 1 if (start == 0) else (start//results + 1) %}
{% set page_count = feed_params['page_count'] | default(1) %}

{% if autohide and page_count > 1 %}
{% set page_nums = pagination_pages(current_page=page, page_count=page_count, max_pages=max_pages, extremes=extremes) %}
<div class='pagination-bar' role="group">
  <a href="{{ " #" if (page==1) else modify_query(start=(page-2)*results) }}"
    class="pagination-stepper{% if page == 1 %} disabled{% endif %}" {% if page==1 %} onclick="return false;" {% endif
    %}>
    <i class="glyphicon glyphicon-chevron-left"></i>
  </a>
  <ul class="pagination">
    {% for page_num in page_nums %}
    {% if loop.index0 > 0 and page_num - page_nums[loop.index0 - 1] > 1 %}
    <li class="disabled"><a>&middot;&middot;&middot;</a></li>
    {% endif %}
    <li {% if page==page_num %}class="active" {% endif %}><a href="{{ modify_query(start=(page_num-1)*results) }}"> {{
        page_num }} </a></li>
    {% endfor %}
  </ul>
  <a href="{{ " #" if (page==page_count) else modify_query(start=page*results) }}"
    class="pagination-stepper{% if page == page_count %} disabled{% endif %}" {% if page==page_count %}
    onclick="return false;" {% endif %}>
    <i class="glyphicon glyphicon-chevron-right"></i>
  </a>
</div>
{% endif %}
{% endif %}
{% endmacro %}

{% macro page_sizer() %}
{% if feed_params %}
{% set results = feed_params['results'] | default(10) %}
<ul class="pagination">
  <li {% if results==5 %}class="active" {% endif %}>
    <a href="{{ modify_query(results=5) }}" title="Show 5 items per page" aria-current="true">5</a>
  </li>
  <li {% if results==10 %}class="active" {% endif %}>
    <a href="{{ modify_query(results=10) }}" title="Show 10 items per page" aria-current="true">10</a>
  </li>
  <li {% if results==20 %}class="active" {% endif %}>
    <a href="{{ modify_query(results=20) }}" title="Show 20 items per page" aria-current="true">20</a>
  </li>
  <span class="text" style="display:inline-flex;text-align:justify;align-items:center;line-height:35px;"> &nbsp;per
    page</span>
</ul>
{% endif %}
{% endmacro %}


{% macro sort_filter() %}
{% if feed_params and get_current_path() == 'feed' %}
{% set tab = feed_params['tab'] | default('Newest') %}
<!-- Index rendering mode switch -->
<div class="row">
  <div class="col-md-11">
    <a href="/feed?tab=Newest" class="btn btn-default btn-card no-underline {% if tab == 'Newest' %} active {% endif %}"
      role="button">
      <span class="index-view-name"> Newest </span>
    </a>
    <a href="/feed?tab=Frequent"
      class="btn btn-default btn-table no-underline {% if tab == 'Frequent' %} active {% endif %} " role="button">
      <span class="index-view-name"> Frequent </span>
    </a>
    <a href="/feed?tab=Vote" class="btn btn-default btn-cluster no-underline {% if tab == 'Vote' %} active {% endif %}"
      role="button">
      <span class="index-view-name"> Vote(s) </span>
    </a>
    <!-- <a class="btn btn-default btn-card no-underline" id="toggle-button" role="button" aria-expanded="false" aria-controls="uql-form">
        <svg class="justify-content: center; display: flex" width="20" height="20" viewBox="0 -5 20 20">
          <path d="M2 4h14v2H2V4Zm2 4h10v2H4V8Zm8 4H6v2h6v-2Z" fill="#06c6b6"></path>
        </svg> Filter
      </a> -->
    <!-- </div> -->
  </div>
</div>
{% endif %}
{% endmacro %}

{% block panel_left %}
<div class="sidebar2 homepage-side-panel">
  <h2>Menu</h2>
  <ul>
    <li>
      <a href="/feed" role="button" class="btn btn-default btn-card no-underline">
        <i class="glyphicon glyphicon-pencil"></i>
        <span class="index-view-name"> Home </span>
      </a>
    </li>
    <li>
      <a href="/table" role="button" class="btn btn-default btn-table no-underline">
        <i class="glyphicon glyphicon-th"></i>
        <span class="index-view-name"> Table </span>
      </a>
    </li>
    <li>
      <a href="/cluster" role="button" class="btn btn-default btn-cluster no-underline">
        <i class="glyphicon glyphicon-th-list"></i>
        <span class="index-view-name"> Cluster </span>
      </a>
    </li>
  </ul>
</div>
{% endblock %}

{% block content %}
<div data-controller="se-uql" data-se-uql-id="" data-se-uql-sanitize-tag-query="false">
  <div class="row">
    <div class="col-md-6">
      {{ sort_filter() }}
    </div>

    <div class="pull-right visible-md-block visible-lg-block">
      {{ page_sizer() }}
    </div>
  </div>

  <!-- <div class="row">
  <div class="col-md-6">
  <form class="form-group form-base" id="uql-form">
    <fieldset class="fieldset">
      <legend class="legend font-style">Tagged with:</legend>
      <div class="radio-inline radio-cluster">
        <input class="radio" type="radio" name="tagModeId" value="Watched">
        <label class="feed-tldr font-style">My subscribed tags</label>
      </div>
      <div class="margin-left: 0px">
        <div class="radio-inline radio-cluster">
          <input class="radio" type="radio" name="tagModeId" value="Watched">
          <label class="feed-tldr font-style">The following tags</label>
          <input type="text" autocomplete="off" tabindex="0" aria-autocomplete="list" aria-haspopup="listbox" role="combobox" aria-expanded="false" placeholder="e.g. python" style="width: 100px;">
        </div>
      </div>
    </fieldset>
    <div>
    </div>
    <button class="btn btn-default btn-card no-underline" style="justify-content: flex-end;" type="button" onclick="applySelection()">Apply</button>
    <button class="btn btn-default btn-card no-underline" style="justify-content: flex-end;" type="reset" id="toggle-button">Cancel</button>
  </form>
</div>
</div> -->
</div>


<div class="col-12">
  {% block inner_content %}
  {% endblock %}
</div>

{# Show pagination at bottom of page unless showing clusters. #}
{% if request.endpoint != 'index.render_cluster' %}
{{ pagination(max_pages=10) }}
{% endif %}

<script type="text/javascript">
    // const form = document.querySelector("#uql-form");
    // const toggleButton = document.querySelector("#toggle-button");

    // // Initially hide the form
    // form.style.display = "none";

    // // Attach an event listener to the toggle button
    // toggleButton.addEventListener("click", () => {
    //   if (form.style.display === "none") {
    //     form.style.display = "block";
    //     toggleButton.setAttribute("aria-expanded", true);
    //   } else {
    //     form.style.display = "none";
    //     toggleButton.setAttribute("aria-expanded", false);
    //   }
    // });

</script>
{% endblock %}

knowledge_repo/app/templates/index-cluster.html
{% extends "index-base.html" %}

{% block header %}

<text style="font-size:32px">Knowledge Clusters {% endblock %}</text>

{% block inner_content %}
<br><br>
<div class="row cluster-header">
  <div class="col-md-14" style='background-color:white'>
    <div class="col-md-2_5 group-by-header">
      <h5> Group posts by:</h5>
    </div>
    <span class="col-md-3 group-by-options">
      <div class="radio-inline radio-cluster">
        <label>
          <input type="radio" name="cluster-radio" id="clusterFolder">Folder
        </label>
      </div>
      <div class="radio-inline radio-cluster">
        <label>
          <input type="radio" name="cluster-radio" id="clusterTags">Tags
        </label>
      </div>
      <div class="radio-inline radio-cluster">
        <label>
          <input type="radio" name="cluster-radio" id="clusterAuthor">Author
        </label>
      </div>
    </span>
    <div class="col-md-2_5 sort-by-header">
      <h5> Sort by:</h5>
    </div>
    <span class="col-md-3 sort-by-options">
      <div class="radio-inline radio-cluster">
        <label>
          <input type="radio" name="sort-radio" id="sortAlpha"> Alphabetically
        </label>
      </div>
      <div class="radio-inline radio-cluster">
        <label>
          <input type="radio" name="sort-radio" id="sortCount">Count
        </label>
      </div>
    </span>
    <div style="clear:both"></div>
  </div>
</div>
<ul id="cluster_list" class="col-md-14;margin-left: 20px;display: inline-flex;">
  {%- for cluster, is_post, count, contents in grouped_data recursive %}
  {%- if is_post %}
  <li class="cluster-list-li" style="list-style-type:circle">
    <a href="{{'/post/' + contents.path|urlencode }}">
      {{ contents.title|replace('_', ' '|title )}}
    </a>
  </li>
  {%- else %}
  {%- if contents|length > 0 and cluster|length > 0 %}
  {% set cluster_id = cluster|replace(' ', '__')|replace('-', '__')|replace('#', '__')|replace('.', '__') %}
  <li id="{{ cluster_id|safe }}" class="cluster_dir cluster-list-li" style="list-style-type:disc">
    <div>
      <h6 style="margin-bottom:0;margin-top:0;margin-left: 10px;">
        {{ [cluster,' (', count, ')'] | join }}
        <i id="{{ cluster_id|safe }}-glyph" class="glyphicon glyphicon-chevron-right cluster-dropdown"></i>
      </h6>
    </div>
  </li>
  <div id="{{ cluster_id|safe }}-content" style="display:none">
    <ul style="margin-top: 0px">
      {{ loop(contents) }}
    </ul>
  </div>
  {%- endif %}
  {%- endif %}
  {%- endfor %}
</ul>
</nav>

{% endblock %}

{% block scripts %}
{{ super() }}
<script src="{{ url_for('static', filename='js/index-cluster.js') }}"></script>
<script type="text/javascript">
  $(document).ready(function () {
    var cluster_button = $(".btn-cluster")[0];
    $(cluster_button).addClass("btn-active");
    var glyphicon = $(".glyphicon-post-org.glyphicon-th-list")[0];
    $(glyphicon).addClass("glyphicon-active");

    var tag = "{{ tag |default('', true)}}";
    var clusterSelected = '#cluster{{ group_by|title }}';
    var sortSelected = '#sort{{ sort_by|title }}';
    var clusterButtons = ["clusterFolder", "clusterTags", "clusterAuthor"];
    var sortButtons = ["sortAlpha", "sortCount"];
    indexClusterJx.addFoldingToGroups();
    indexClusterJx.clickTag(tag);
    clusterSelected = indexClusterJx.getClusterSelected(clusterSelected);
    sortSelected = indexClusterJx.getSortSelected(sortSelected);
    $(clusterSelected)[0].setAttribute("checked", "checked")
    $(sortSelected)[0].setAttribute("checked", "checked")
    indexClusterJx.formatButtons(clusterSelected, clusterButtons, sortSelected, sortButtons);

    function search() {
      indexClusterJx.refreshPage(clusterSelected, sortSelected);
    }
  })
</script>
{% endblock %}

knowledge_repo/app/templates/upload_page.html
{% extends "base.html" %}

{% block content %}
      <form action = "{{ url_for('api.upload_post') }}" method=post enctype = "multipart/form-data">
<table align="center">
<tr> <td style="padding:5px;">Select File to upload     <td style="padding:5px;">      <input type = "file" name ="file" onclick="googleAnalyticsObject.googleAnalytics(gaUpload,'ipython_upload',categoryKr);"/> </tr>
<tr> <td style="padding:5px;">Select Repository     <td style="padding:5px;">      <select name="repo">      
{% for pid,kr in krs %}
<option value={{pid}}/{{kr}}>{{kr}}</option>
{% endfor %}
</select>
</tr>

<tr><td style="padding:5px;">Path to upload post to  <td style="padding:5px;"> <input type = "text" name="path" /> </tr>
<tr><td style="padding:10px;" align="center" colspan=2>         <input type = "submit" value="Upload Post" onclick="googleAnalyticsObject.googleAnalytics(gaUpload,'post_upload',categoryKr);"/>   </tr>
       </table> </form>
{% endblock %}